/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rechnung.gui;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import rechnung.tools.DBTools;
import rechnung.tools.Rechnung;

/**
 *
 * @author info
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AusgabeWindow = new javax.swing.JTextArea();
        MainMenu = new javax.swing.JMenuBar();
        MenuRechnung = new javax.swing.JMenu();
        RechnungAnz = new javax.swing.JMenuItem();
        RechnungNeu = new javax.swing.JMenuItem();
        RechnungBea = new javax.swing.JMenuItem();
        RechnungEntf = new javax.swing.JMenuItem();
        MenuTabellen = new javax.swing.JMenu();
        MenuCustomer = new javax.swing.JMenuItem();
        MenuProduct = new javax.swing.JMenuItem();
        MenuItem = new javax.swing.JMenuItem();
        MenuInvoice = new javax.swing.JMenuItem();
        SqlMode = new javax.swing.JMenu();
        DbChange = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(853, 1263));

        AusgabeWindow.setColumns(20);
        AusgabeWindow.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        AusgabeWindow.setRows(5);
        AusgabeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(AusgabeWindow);

        MenuRechnung.setText("Rechnungen");

        RechnungAnz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        RechnungAnz.setText("Rechnung Anzeigen");
        RechnungAnz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechnungAnzActionPerformed(evt);
            }
        });
        MenuRechnung.add(RechnungAnz);

        RechnungNeu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        RechnungNeu.setText("Neue Rechnung");
        RechnungNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechnungNeuActionPerformed(evt);
            }
        });
        MenuRechnung.add(RechnungNeu);

        RechnungBea.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        RechnungBea.setText("Rechnung bearbeiten");
        RechnungBea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechnungBeaActionPerformed(evt);
            }
        });
        MenuRechnung.add(RechnungBea);

        RechnungEntf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        RechnungEntf.setText("Rechnung Löschen");
        RechnungEntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechnungEntfActionPerformed(evt);
            }
        });
        MenuRechnung.add(RechnungEntf);

        MainMenu.add(MenuRechnung);

        MenuTabellen.setText("Tabellen");

        MenuCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        MenuCustomer.setText("Customer");
        MenuCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCustomerActionPerformed(evt);
            }
        });
        MenuTabellen.add(MenuCustomer);

        MenuProduct.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        MenuProduct.setText("Product");
        MenuProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductActionPerformed(evt);
            }
        });
        MenuTabellen.add(MenuProduct);

        MenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        MenuItem.setText("Item");
        MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActionPerformed(evt);
            }
        });
        MenuTabellen.add(MenuItem);

        MenuInvoice.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        MenuInvoice.setText("Invoice");
        MenuInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInvoiceActionPerformed(evt);
            }
        });
        MenuTabellen.add(MenuInvoice);

        MainMenu.add(MenuTabellen);

        SqlMode.setText("SQL-Mode");

        DbChange.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        DbChange.setText("DB Change");
        DbChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DbChangeActionPerformed(evt);
            }
        });
        SqlMode.add(DbChange);

        MainMenu.add(SqlMode);

        setJMenuBar(MainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCustomerActionPerformed
        try (ResultSet rs = DBTools.getCon().createStatement().executeQuery("select * from customer")) {
            AusgabeWindow.setText(ausgabe(rs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MenuCustomerActionPerformed

    private void RechnungNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechnungNeuActionPerformed
       new NewRechnung().setVisible(true);
    }//GEN-LAST:event_RechnungNeuActionPerformed

    private void RechnungBeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechnungBeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RechnungBeaActionPerformed

    private void RechnungEntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechnungEntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RechnungEntfActionPerformed

    private void RechnungAnzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechnungAnzActionPerformed
        rechnungAnz();
    }//GEN-LAST:event_RechnungAnzActionPerformed

    private void MenuProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductActionPerformed
                try (ResultSet rs = DBTools.getCon().createStatement().executeQuery("select * from Product")) {
            AusgabeWindow.setText(ausgabe(rs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MenuProductActionPerformed

    private void MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActionPerformed
                try (ResultSet rs = DBTools.getCon().createStatement().executeQuery("select * from Item")) {
            AusgabeWindow.setText(ausgabe(rs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MenuItemActionPerformed

    private void MenuInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInvoiceActionPerformed
                try (ResultSet rs = DBTools.getCon().createStatement().executeQuery("select * from Invoice")) {
            AusgabeWindow.setText(ausgabe(rs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MenuInvoiceActionPerformed

    private void DbChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DbChangeActionPerformed
        String sqlcommand = JOptionPane.showInputDialog("SQL-Befehel Eingeben :");
        try (ResultSet rs = DBTools.getCon().createStatement().executeQuery(sqlcommand)) {
            JOptionPane.showMessageDialog(null, "SQL-Eingriff Erfolgreich");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_DbChangeActionPerformed
    
    public String ausgabe(ResultSet rs) throws SQLException {
        
        ResultSetMetaData mdat = rs.getMetaData();                           //Erstellt ein Objekt in der die Inf. gespeichert werden

        int sp = mdat.getColumnCount();
        
        StringBuilder z2 = new StringBuilder();                                                       //Erstellt den String z2
        String[] gstr = new String[mdat.getColumnCount()];                   //Erstellt den Array gstr & fügt die Spalten Zahl ein
        for (int i = 0; i < mdat.getColumnCount(); i++) {
            z2.append("|%");
            z2.append(mdat.getColumnDisplaySize(i + 1));
            z2.append("s");                                                    //Erstellt einen String mit der Tab. formatierung
        }
        z2.append("%n");                                                    //ergänzt noch das ende (optisch)
        String form = z2.toString();
        StringBuilder out = new StringBuilder();
        while (rs.next()) {
            for (int i = 1; i <= mdat.getColumnCount(); i++) {
                gstr[i - 1] = rs.getString(i);
            }
            out.append(String.format(form, gstr));
        }
        return out.toString();
    }
    
    private void rechnungAnz() {
        String RechnungsnummerIn = JOptionPane.showInputDialog("Rechnungsnummer Eingeben");
        RechnungOut(RechnungsnummerIn);
    }
    
    private void RechnungOut(String RechnungsnummerIn) {
        try {
            int rIn = Integer.parseInt(RechnungsnummerIn);
            Rechnung rino = Rechnung.getRechnung(DBTools.getCon(), rIn);
            System.out.println(rino);
            AusgabeWindow.setText(rino.toString());
        } catch (Exception E) {
            rechnungAnz();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AusgabeWindow;
    private javax.swing.JMenuItem DbChange;
    private javax.swing.JMenuBar MainMenu;
    private javax.swing.JMenuItem MenuCustomer;
    private javax.swing.JMenuItem MenuInvoice;
    private javax.swing.JMenuItem MenuItem;
    private javax.swing.JMenuItem MenuProduct;
    private javax.swing.JMenu MenuRechnung;
    private javax.swing.JMenu MenuTabellen;
    private javax.swing.JMenuItem RechnungAnz;
    private javax.swing.JMenuItem RechnungBea;
    private javax.swing.JMenuItem RechnungEntf;
    private javax.swing.JMenuItem RechnungNeu;
    private javax.swing.JMenu SqlMode;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}

