/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rechnung.gui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import rechnung.tools.DBTools;

/**
 *
 * @author info
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AusgabeWindow = new javax.swing.JTextArea();
        MainMenu = new javax.swing.JMenuBar();
        MenuDatei = new javax.swing.JMenu();
        MenuTabellen = new javax.swing.JMenu();
        MenuKunden = new javax.swing.JMenuItem();
        MenuItem2 = new javax.swing.JMenuItem();
        MenuKäufe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));

        Search.setText("Rechnungsnummer");

        AusgabeWindow.setColumns(20);
        AusgabeWindow.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        AusgabeWindow.setRows(5);
        AusgabeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AusgabeWindow.setEnabled(false);
        jScrollPane1.setViewportView(AusgabeWindow);

        MenuDatei.setText("Datei");
        MainMenu.add(MenuDatei);

        MenuTabellen.setText("Tabellen");

        MenuKunden.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        MenuKunden.setText("Kunden");
        MenuKunden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKundenActionPerformed(evt);
            }
        });
        MenuTabellen.add(MenuKunden);

        MenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        MenuItem2.setText("MenuProdukte");
        MenuTabellen.add(MenuItem2);

        MenuKäufe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        MenuKäufe.setText("Käufe");
        MenuTabellen.add(MenuKäufe);

        MainMenu.add(MenuTabellen);

        setJMenuBar(MainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuKundenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKundenActionPerformed
        try (ResultSet rs = DBTools.getCon().createStatement().executeQuery("select * from customer")){
            AusgabeWindow.setText(ausgabe(rs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MenuKundenActionPerformed

    public String ausgabe(ResultSet rs) throws SQLException {

        ResultSetMetaData mdat = rs.getMetaData();                           //Erstellt ein Objekt in der die Inf. gespeichert werden

        int sp = mdat.getColumnCount();

        StringBuilder z2 = new StringBuilder();                                                       //Erstellt den String z2
        String[] gstr = new String[mdat.getColumnCount()];                   //Erstellt den Array gstr & fügt die Spalten Zahl ein
        for (int i = 0; i < mdat.getColumnCount(); i++) {
            z2.append("|%");
            z2.append(mdat.getColumnDisplaySize(i+1));
            z2.append("s");                                                    //Erstellt einen String mit der Tab. formatierung
        }
        z2.append("%n");                                                    //ergänzt noch das ende (optisch)
        String form = z2.toString();
        StringBuilder out = new StringBuilder();
        while (rs.next()) {
            for (int i = 1; i <= mdat.getColumnCount(); i++) {
                gstr[i - 1] = rs.getString(i);
            }
            out.append(String.format(form, gstr));
        }
        return out.toString();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AusgabeWindow;
    private javax.swing.JMenuBar MainMenu;
    private javax.swing.JMenu MenuDatei;
    private javax.swing.JMenuItem MenuItem2;
    private javax.swing.JMenuItem MenuKunden;
    private javax.swing.JMenuItem MenuKäufe;
    private javax.swing.JMenu MenuTabellen;
    private javax.swing.JTextField Search;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
